name: "git-push"
description: "Commit and push changes to a branch"

inputs:
  git_user:
    description: "Git user.name for commit author"
    required: false
    default: ${{ github.actor }}
  commit_message:
    description: "Commit message for the push"
    required: true
  files:
    description: 'Files to add (space separated, or use "." for all)'
    required: false
    default: "."
  branch:
    description: "Push Branch"
    required: false
    default: ${{ github.ref_name }}

runs:
  using: "composite"
  steps:
    - name: Switches to push_branch@latest along with changes.
      shell: bash
      run: |
        git add .
        git stash
        git fetch origin ${{ inputs.branch }}:${{ inputs.branch }}
        git switch ${{ inputs.branch }}
        git stash pop
        git reset

    - name: Set up Git config
      shell: bash
      run: |
        git config --global user.name "${{ inputs.git_user }}"
        git config --global user.email "${{ inputs.git_user }}@users.noreply.github.com"
        git add ${{ inputs.files }}
        git commit -m "${{ inputs.commit_message }}"
        git push origin ${{ inputs.branch }}
