name: "git-push"
description: "Commit and push changes to a branch"

inputs:
  git_user:
    description: "Git user.name for commit author"
    required: false
    default: ${{ github.actor }}
  commit_message:
    description: "Commit message for the push"
    required: true
  files:
    description: 'Files to add (space separated, or use "." for all)'
    required: false
    default: "."
  branch:
    description: "Push Branch"
    required: false
    default: ${{ github.ref_name }}

runs:
  using: "composite"
  steps:
    - name: Switches to push_branch@latest along with changes.
      shell: bash
      env:
        PUSH_BRANCH: ${{ inputs.branch }}
      run: |
        git add . && git stash
        git fetch origin $PUSH_BRANCH:$PUSH_BRANCH
        git switch $PUSH_BRANCH
        echo "➡️ Applying stash"
        git stash pop || git checkout --theirs .
        git stash drop
        echo "➡️ Ready to push"

    - name: Set up Git config
      shell: bash
      env:
        GIT_USER: ${{ inputs.git_user }}
        FILES: ${{ inputs.files }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        PUSH_BRANCH: ${{ inputs.branch }}
      run: |
        git config --global user.name "$GIT_USER"
        git config --global user.email "${GIT_USER}@users.noreply.github.com"
        echo "➡️ adding files"
        git reset && git add $FILES
        git status
        git commit -m "$COMMIT_MESSAGE"
        git push origin $PUSH_BRANCH
