name: "git-push"
description: "Commit and push changes to a branch"
inputs:
  git_user:
    description: "Git user.name for commit author"
    required: false
    default: ${{ github.actor }}
  commit_message:
    description: "Commit message for the push"
    required: true
  files:
    description: 'Files to add (space separated, or use "." for all)'
    required: false
    default: "."
  branch:
    description: "Push Branch"
    required: false
    default: ${{ github.ref_name }}
runs:
  using: "composite"
  steps:
    - name: Set up Git config
      run: |
        git config --global user.name "${{ inputs.git_user }}"
        git config --global user.email "${{ inputs.git_user }}@users.noreply.github.com"

    - name: Add files and Commit
      run: |
        git add ${{ inputs.files }}
        git commit -m "${{ inputs.commit_message }}"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin ${{ inputs.branch }}
