name: Commit and Push

on:
  workflow_call:
    inputs:
      git_user:
        description: "Git user.name for commit author"
        required: false
        default: ${{ github.actor }}
        type: string
      commit_message:
        description: "Commit message for the push"
        required: true
        type: string
      files:
        description: 'Files to add (space separated, or use "." for all)'
        required: false
        default: "."
        type: string
      branch:
        description: "Push Branch"
        required: false
        default: ${{ github.ref_name }}
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  git-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git config
        run: |
          git config --global user.name "${{ inputs.git_user }}"
          git config --global user.email "${{ inputs.git_user }}@users.noreply.github.com"

      - name: Add files
        run: git add ${{ inputs.files }}

      - name: Commit changes
        run: git commit -m "${{ inputs.commit_message }}"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin ${{ inputs.branch }}
